### ISSUE TITLE
API prototyping

### ISSUE THREAD

**Issue by Chengjing-314** [cse110-fall21-group9/cse110-fa21-group9#5]
Please get yourself familiar with the Edamam API, try to build a few prototypes according to our pitch.

**Comment by haxoc** [comment]
Made a simple request thing with `XMLHttpRequest`. I think we will use the fetch api though for the actual app, I will work on that later today.

**Comment by haxoc** [comment]
I prototyped both EDMAM and Spoonacular. It seems that by first glance EDMAM would suite us better, but it doesn't have a way to get recipe instructions/steps, so we are going to have to use spoonacular. There shouldn't be a difference for the front end, in order to solve the added complexity we will just have to handle it in the backend and make multiple calls per frontend request. @Chengjing-314 anything else to add?
